import type { EmitterConfig } from "./types";

// Predefined emitter configurations
export const EMITTER_PRESETS = {
  lineAppearRibbon: {
    name: "line-ribbon",
    emitMode: "burst",
    count: 32,
    life: 1.2,
    lifeVar: 0.4,
    size: 8,
    sizeVar: 3,
    speed: 40,
    speedVar: 15,
    angle: -90,
    spread: 25,
    gravity: -8,
    drag: 0.08,
    alpha: 0.5,
    blend: "lighter",
    spawnShape: "alongStroke",
    spawnLength: 0.3,
    followStroke: true,
    easeFn: "cosine",
  } as EmitterConfig,

  lineAppearSpores: {
    name: "line-spores",
    emitMode: "burst",
    count: 80,
    life: 1.8,
    size: 5,
    sizeVar: 2,
    speed: 25,
    speedVar: 15,
    spread: 180,
    gravity: 3,
    drag: 0.15,
    alpha: 0.3,
    blend: "lighter",
    spawnShape: "line",
    spawnLength: 50,
  } as EmitterConfig,

  suspendDust: {
    name: "suspend-dust",
    emitMode: "pulse",
    count: 10,
    life: 2.2,
    size: 5,
    sizeVar: 3,
    speed: 12,
    speedVar: 6,
    spread: 360,
    gravity: 5,
    drag: 0.25,
    alpha: 0.18,
    blend: "source-over",
    spawnShape: "line",
    spawnLength: 40,
  } as EmitterConfig,

  resumeSparks: {
    name: "resume-sparks",
    emitMode: "burst",
    count: 28,
    life: 0.65,
    size: 3,
    sizeVar: 2,
    speed: 90,
    speedVar: 40,
    spread: 180,
    gravity: -20,
    drag: 0.08,
    alpha: 0.7,
    blend: "lighter",
    spawnShape: "line",
    spawnLength: 12,
  } as EmitterConfig,

  closeCrumble: {
    name: "close-crumble",
    emitMode: "burst",
    count: 60,
    life: 2.0,
    lifeVar: 0.5,
    size: 7,
    sizeVar: 4,
    speed: 25,
    speedVar: 15,
    angle: 90,
    spread: 45,
    gravity: 60,
    drag: 0.05,
    alpha: 0.6,
    blend: "source-over",
    spawnShape: "line",
    spawnLength: 50,
  } as EmitterConfig,

  stationPop: {
    name: "station-pop",
    emitMode: "burst",
    count: 8,
    life: 0.45,
    size: 8,
    sizeVar: 3,
    speed: 60,
    speedVar: 25,
    spread: 360,
    gravity: 35,
    drag: 0.18,
    alpha: 0.6,
    blend: "lighter",
    spawnShape: "point",
  } as EmitterConfig,

  stationSuspendFade: {
    name: "station-suspend-fade",
    emitMode: "burst",
    count: 8,
    life: 1.2,
    lifeVar: 0.3,
    size: 6,
    sizeVar: 2,
    speed: 15,
    speedVar: 8,
    spread: 360,
    gravity: 8,
    drag: 0.15,
    alpha: 0.4,
    blend: "source-over",
    spawnShape: "point",
  } as EmitterConfig,

  stationResumeGlow: {
    name: "station-resume-glow",
    emitMode: "burst",
    count: 8,
    life: 0.8,
    lifeVar: 0.2,
    size: 5,
    sizeVar: 2,
    speed: 35,
    speedVar: 15,
    spread: 360,
    gravity: -5,
    drag: 0.12,
    alpha: 0.6,
    blend: "lighter",
    spawnShape: "point",
  } as EmitterConfig,
} as const;
