import type { LineEmitterConfig, PointEmitterConfig } from "./config";

export const EMITTER_CONFIGS = {
  lineOpen: {
    type: "line",
    name: "lineOpen",
    spawnRadius: 8,
    zBias: 56,
    zVar: 30,
    duration: 0.5,
    rate: 0.5,
    emission: {
      life: 1.15,
      lifeVar: 0.25,
      size: 12,
      sizeVar: 4,
      speed: 110,
      speedVar: 34,
      spreadDeg: 80,
      gravityZ: 6,
      buoyancyZ: 28,
      drag: 0.985,
      angularVar: 3.2,
      blend: "lighter",
    },
  } as LineEmitterConfig,
  lineSuspend: {
    type: "line",
    name: "lineSuspend",
    spawnRadius: 6,
    zBias: 8,
    zVar: 8,
    burstDensity: 0.4,
    emission: {
      life: 1.6,
      lifeVar: 0.3,
      size: 8,
      sizeVar: 2,
      speed: 22,
      speedVar: 10,
      spreadDeg: 160,
      gravityZ: 12,
      buoyancyZ: 10,
      drag: 0.94,
      angularVar: 1.0,
      blend: "source-over",
    },
  } as LineEmitterConfig,
  lineResume: {
    type: "line",
    name: "lineResume",
    spawnRadius: 6,
    zBias: 36,
    zVar: 20,
    burstDensity: 0.2,
    emission: {
      life: 0.9,
      lifeVar: 0.2,
      size: 8,
      sizeVar: 2,
      speed: 140,
      speedVar: 40,
      spreadDeg: 50,
      gravityZ: 2,
      buoyancyZ: 42,
      drag: 0.98,
      angularVar: 6.0,
      blend: "lighter",
    },
  } as LineEmitterConfig,
  lineClose: {
    type: "line",
    name: "lineClose",
    spawnRadius: 10,
    zBias: -30,
    zVar: 30,
    burstDensity: 0.4,
    emission: {
      life: 1.4,
      lifeVar: 0.3,
      size: 14,
      sizeVar: 6,
      speed: 26,
      speedVar: 12,
      spreadDeg: 110,
      gravityZ: -120,
      buoyancyZ: 0,
      drag: 0.96,
      angularVar: 2.6,
      blend: "source-over",
    },
  } as LineEmitterConfig,
  stationOpen: {
    type: "point",
    name: "stationOpen",
    spawnRadius: 5,
    zBias: 40,
    zVar: 20,
    duration: 0.5,
    rate: 20,
    emission: {
      life: 1.0,
      lifeVar: 0.2,
      size: 10,
      sizeVar: 3,
      speed: 80,
      speedVar: 25,
      spreadDeg: 90,
      gravityZ: 8,
      buoyancyZ: 20,
      drag: 0.98,
      angularVar: 3.0,
      blend: "lighter",
    },
  } as PointEmitterConfig,
  stationResume: {
    type: "point",
    name: "stationResume",
    spawnRadius: 4,
    zBias: 30,
    zVar: 15,
    duration: 0.2,
    rate: 40,
    emission: {
      life: 0.8,
      lifeVar: 0.15,
      size: 8,
      sizeVar: 2,
      speed: 60,
      speedVar: 20,
      spreadDeg: 70,
      gravityZ: 5,
      buoyancyZ: 15,
      drag: 0.98,
      angularVar: 2.5,
      blend: "lighter",
    },
  } as PointEmitterConfig,
  stationSuspend: {
    type: "point",
    name: "stationSuspend",
    spawnRadius: 4,
    zBias: 5,
    zVar: 12,
    duration: 0.2,
    rate: 40,
    emission: {
      life: 0.8,
      lifeVar: 0.2,
      size: 8,
      sizeVar: 2,
      speed: 18,
      speedVar: 8,
      spreadDeg: 140,
      gravityZ: 10,
      buoyancyZ: 8,
      drag: 0.95,
      angularVar: 1.0,
      blend: "source-over",
    },
  } as PointEmitterConfig,
  stationClose: {
    type: "point",
    name: "stationClose",
    spawnRadius: 6,
    zBias: -20,
    zVar: 20,
    duration: 0.3,
    rate: 50,
    emission: {
      life: 1.0,
      lifeVar: 0.25,
      size: 10,
      sizeVar: 4,
      speed: 20,
      speedVar: 10,
      spreadDeg: 100,
      gravityZ: -80,
      buoyancyZ: 0,
      drag: 0.96,
      angularVar: 2.0,
      blend: "source-over",
    },
  } as PointEmitterConfig,
};
